(cl:defpackage schunk_api-msg
  (:use )
  (:export
   "<JOINTDATAPOWERBALL>"
   "JOINTDATAPOWERBALL"
   "<POSITIONJOINTSPACE>"
   "POSITIONJOINTSPACE"
   "<POSITIONCOORDSPACE>"
   "POSITIONCOORDSPACE"
   "<INITHALT>"
   "INITHALT"
  ))

