/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/powerball/rpi_robotics_work/schunk_workspace/src/schunk_api/srv/PositionAPICoordSpace.srv
 *
 */


#ifndef SCHUNK_API_MESSAGE_POSITIONAPICOORDSPACEREQUEST_H
#define SCHUNK_API_MESSAGE_POSITIONAPICOORDSPACEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace schunk_api
{
template <class ContainerAllocator>
struct PositionAPICoordSpaceRequest_
{
  typedef PositionAPICoordSpaceRequest_<ContainerAllocator> Type;

  PositionAPICoordSpaceRequest_()
    : xCoord(0.0)
    , yCoord(0.0)
    , zCoord(0.0)
    , quatX(0.0)
    , quatY(0.0)
    , quatZ(0.0)
    , quatW(0.0)  {
    }
  PositionAPICoordSpaceRequest_(const ContainerAllocator& _alloc)
    : xCoord(0.0)
    , yCoord(0.0)
    , zCoord(0.0)
    , quatX(0.0)
    , quatY(0.0)
    , quatZ(0.0)
    , quatW(0.0)  {
    }



   typedef double _xCoord_type;
  _xCoord_type xCoord;

   typedef double _yCoord_type;
  _yCoord_type yCoord;

   typedef double _zCoord_type;
  _zCoord_type zCoord;

   typedef double _quatX_type;
  _quatX_type quatX;

   typedef double _quatY_type;
  _quatY_type quatY;

   typedef double _quatZ_type;
  _quatZ_type quatZ;

   typedef double _quatW_type;
  _quatW_type quatW;




  typedef boost::shared_ptr< ::schunk_api::PositionAPICoordSpaceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::schunk_api::PositionAPICoordSpaceRequest_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct PositionAPICoordSpaceRequest_

typedef ::schunk_api::PositionAPICoordSpaceRequest_<std::allocator<void> > PositionAPICoordSpaceRequest;

typedef boost::shared_ptr< ::schunk_api::PositionAPICoordSpaceRequest > PositionAPICoordSpaceRequestPtr;
typedef boost::shared_ptr< ::schunk_api::PositionAPICoordSpaceRequest const> PositionAPICoordSpaceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::schunk_api::PositionAPICoordSpaceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::schunk_api::PositionAPICoordSpaceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace schunk_api

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'schunk_api': ['/home/powerball/rpi_robotics_work/schunk_workspace/src/schunk_api/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::schunk_api::PositionAPICoordSpaceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::schunk_api::PositionAPICoordSpaceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::schunk_api::PositionAPICoordSpaceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::schunk_api::PositionAPICoordSpaceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::schunk_api::PositionAPICoordSpaceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::schunk_api::PositionAPICoordSpaceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::schunk_api::PositionAPICoordSpaceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e03157376959499c94bb7df7a77bf0e0";
  }

  static const char* value(const ::schunk_api::PositionAPICoordSpaceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe03157376959499cULL;
  static const uint64_t static_value2 = 0x94bb7df7a77bf0e0ULL;
};

template<class ContainerAllocator>
struct DataType< ::schunk_api::PositionAPICoordSpaceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "schunk_api/PositionAPICoordSpaceRequest";
  }

  static const char* value(const ::schunk_api::PositionAPICoordSpaceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::schunk_api::PositionAPICoordSpaceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 xCoord\n\
float64 yCoord\n\
float64 zCoord\n\
float64 quatX\n\
float64 quatY\n\
float64 quatZ\n\
float64 quatW\n\
";
  }

  static const char* value(const ::schunk_api::PositionAPICoordSpaceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::schunk_api::PositionAPICoordSpaceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.xCoord);
      stream.next(m.yCoord);
      stream.next(m.zCoord);
      stream.next(m.quatX);
      stream.next(m.quatY);
      stream.next(m.quatZ);
      stream.next(m.quatW);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct PositionAPICoordSpaceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::schunk_api::PositionAPICoordSpaceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::schunk_api::PositionAPICoordSpaceRequest_<ContainerAllocator>& v)
  {
    s << indent << "xCoord: ";
    Printer<double>::stream(s, indent + "  ", v.xCoord);
    s << indent << "yCoord: ";
    Printer<double>::stream(s, indent + "  ", v.yCoord);
    s << indent << "zCoord: ";
    Printer<double>::stream(s, indent + "  ", v.zCoord);
    s << indent << "quatX: ";
    Printer<double>::stream(s, indent + "  ", v.quatX);
    s << indent << "quatY: ";
    Printer<double>::stream(s, indent + "  ", v.quatY);
    s << indent << "quatZ: ";
    Printer<double>::stream(s, indent + "  ", v.quatZ);
    s << indent << "quatW: ";
    Printer<double>::stream(s, indent + "  ", v.quatW);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCHUNK_API_MESSAGE_POSITIONAPICOORDSPACEREQUEST_H
