/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/powerball/rpi_robotics_work/schunk_workspace/src/cob_driver/cob_base_drive_chain/srv/ElmoRecorderReadout.srv
 *
 */


#ifndef COB_BASE_DRIVE_CHAIN_MESSAGE_ELMORECORDERREADOUT_H
#define COB_BASE_DRIVE_CHAIN_MESSAGE_ELMORECORDERREADOUT_H

#include <ros/service_traits.h>


#include <cob_base_drive_chain/ElmoRecorderReadoutRequest.h>
#include <cob_base_drive_chain/ElmoRecorderReadoutResponse.h>


namespace cob_base_drive_chain
{

struct ElmoRecorderReadout
{

typedef ElmoRecorderReadoutRequest Request;
typedef ElmoRecorderReadoutResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ElmoRecorderReadout
} // namespace cob_base_drive_chain


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cob_base_drive_chain::ElmoRecorderReadout > {
  static const char* value()
  {
    return "58d03a96e0b56a380d625c18335fb081";
  }

  static const char* value(const ::cob_base_drive_chain::ElmoRecorderReadout&) { return value(); }
};

template<>
struct DataType< ::cob_base_drive_chain::ElmoRecorderReadout > {
  static const char* value()
  {
    return "cob_base_drive_chain/ElmoRecorderReadout";
  }

  static const char* value(const ::cob_base_drive_chain::ElmoRecorderReadout&) { return value(); }
};


// service_traits::MD5Sum< ::cob_base_drive_chain::ElmoRecorderReadoutRequest> should match 
// service_traits::MD5Sum< ::cob_base_drive_chain::ElmoRecorderReadout > 
template<>
struct MD5Sum< ::cob_base_drive_chain::ElmoRecorderReadoutRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cob_base_drive_chain::ElmoRecorderReadout >::value();
  }
  static const char* value(const ::cob_base_drive_chain::ElmoRecorderReadoutRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cob_base_drive_chain::ElmoRecorderReadoutRequest> should match 
// service_traits::DataType< ::cob_base_drive_chain::ElmoRecorderReadout > 
template<>
struct DataType< ::cob_base_drive_chain::ElmoRecorderReadoutRequest>
{
  static const char* value()
  {
    return DataType< ::cob_base_drive_chain::ElmoRecorderReadout >::value();
  }
  static const char* value(const ::cob_base_drive_chain::ElmoRecorderReadoutRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cob_base_drive_chain::ElmoRecorderReadoutResponse> should match 
// service_traits::MD5Sum< ::cob_base_drive_chain::ElmoRecorderReadout > 
template<>
struct MD5Sum< ::cob_base_drive_chain::ElmoRecorderReadoutResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cob_base_drive_chain::ElmoRecorderReadout >::value();
  }
  static const char* value(const ::cob_base_drive_chain::ElmoRecorderReadoutResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cob_base_drive_chain::ElmoRecorderReadoutResponse> should match 
// service_traits::DataType< ::cob_base_drive_chain::ElmoRecorderReadout > 
template<>
struct DataType< ::cob_base_drive_chain::ElmoRecorderReadoutResponse>
{
  static const char* value()
  {
    return DataType< ::cob_base_drive_chain::ElmoRecorderReadout >::value();
  }
  static const char* value(const ::cob_base_drive_chain::ElmoRecorderReadoutResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COB_BASE_DRIVE_CHAIN_MESSAGE_ELMORECORDERREADOUT_H
