/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/powerball/rpi_robotics_work/schunk_workspace/src/cob_common/cob_srvs/srv/SetMaxVel.srv
 *
 */


#ifndef COB_SRVS_MESSAGE_SETMAXVEL_H
#define COB_SRVS_MESSAGE_SETMAXVEL_H

#include <ros/service_traits.h>


#include <cob_srvs/SetMaxVelRequest.h>
#include <cob_srvs/SetMaxVelResponse.h>


namespace cob_srvs
{

struct SetMaxVel
{

typedef SetMaxVelRequest Request;
typedef SetMaxVelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetMaxVel
} // namespace cob_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cob_srvs::SetMaxVel > {
  static const char* value()
  {
    return "5212ea5f4e683819f4e395ad0eb8ae8c";
  }

  static const char* value(const ::cob_srvs::SetMaxVel&) { return value(); }
};

template<>
struct DataType< ::cob_srvs::SetMaxVel > {
  static const char* value()
  {
    return "cob_srvs/SetMaxVel";
  }

  static const char* value(const ::cob_srvs::SetMaxVel&) { return value(); }
};


// service_traits::MD5Sum< ::cob_srvs::SetMaxVelRequest> should match 
// service_traits::MD5Sum< ::cob_srvs::SetMaxVel > 
template<>
struct MD5Sum< ::cob_srvs::SetMaxVelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cob_srvs::SetMaxVel >::value();
  }
  static const char* value(const ::cob_srvs::SetMaxVelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cob_srvs::SetMaxVelRequest> should match 
// service_traits::DataType< ::cob_srvs::SetMaxVel > 
template<>
struct DataType< ::cob_srvs::SetMaxVelRequest>
{
  static const char* value()
  {
    return DataType< ::cob_srvs::SetMaxVel >::value();
  }
  static const char* value(const ::cob_srvs::SetMaxVelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cob_srvs::SetMaxVelResponse> should match 
// service_traits::MD5Sum< ::cob_srvs::SetMaxVel > 
template<>
struct MD5Sum< ::cob_srvs::SetMaxVelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cob_srvs::SetMaxVel >::value();
  }
  static const char* value(const ::cob_srvs::SetMaxVelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cob_srvs::SetMaxVelResponse> should match 
// service_traits::DataType< ::cob_srvs::SetMaxVel > 
template<>
struct DataType< ::cob_srvs::SetMaxVelResponse>
{
  static const char* value()
  {
    return DataType< ::cob_srvs::SetMaxVel >::value();
  }
  static const char* value(const ::cob_srvs::SetMaxVelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COB_SRVS_MESSAGE_SETMAXVEL_H
