/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/powerball/rpi_robotics_work/schunk_workspace/src/cob_driver/cob_light/srv/SetLightMode.srv
 *
 */


#ifndef COB_LIGHT_MESSAGE_SETLIGHTMODEREQUEST_H
#define COB_LIGHT_MESSAGE_SETLIGHTMODEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <cob_light/LightMode.h>

namespace cob_light
{
template <class ContainerAllocator>
struct SetLightModeRequest_
{
  typedef SetLightModeRequest_<ContainerAllocator> Type;

  SetLightModeRequest_()
    : mode()  {
    }
  SetLightModeRequest_(const ContainerAllocator& _alloc)
    : mode(_alloc)  {
    }



   typedef  ::cob_light::LightMode_<ContainerAllocator>  _mode_type;
  _mode_type mode;




  typedef boost::shared_ptr< ::cob_light::SetLightModeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cob_light::SetLightModeRequest_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct SetLightModeRequest_

typedef ::cob_light::SetLightModeRequest_<std::allocator<void> > SetLightModeRequest;

typedef boost::shared_ptr< ::cob_light::SetLightModeRequest > SetLightModeRequestPtr;
typedef boost::shared_ptr< ::cob_light::SetLightModeRequest const> SetLightModeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cob_light::SetLightModeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cob_light::SetLightModeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cob_light

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/hydro/share/actionlib_msgs/cmake/../msg'], 'cob_light': ['/home/powerball/rpi_robotics_work/schunk_workspace/src/cob_driver/cob_light/msg', '/home/powerball/rpi_robotics_work/schunk_workspace/devel/share/cob_light/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cob_light::SetLightModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cob_light::SetLightModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cob_light::SetLightModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cob_light::SetLightModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cob_light::SetLightModeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cob_light::SetLightModeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cob_light::SetLightModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bfc3763d6f527fc6f26b234ea07ebf58";
  }

  static const char* value(const ::cob_light::SetLightModeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbfc3763d6f527fc6ULL;
  static const uint64_t static_value2 = 0xf26b234ea07ebf58ULL;
};

template<class ContainerAllocator>
struct DataType< ::cob_light::SetLightModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cob_light/SetLightModeRequest";
  }

  static const char* value(const ::cob_light::SetLightModeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cob_light::SetLightModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cob_light/LightMode mode\n\
\n\
================================================================================\n\
MSG: cob_light/LightMode\n\
uint8 mode\n\
uint8 NONE = 0 			# will turn everything off\n\
uint8 STATIC = 1 		# will change the LEDs to \"color\"\n\
uint8 FLASH = 2 		# will change the LEDs frequently with \"frequency\" from \"color\" to black\n\
uint8 BREATH = 3 		# will change the LEDs smoothly with \"frequency\" from \"color\" to black\n\
uint8 BREATH_COLOR = 4 	# will change the LEDs smoothly with \"frequency\" from \"color\" to black\n\
						# and flips color in time\n\
uint8 FADE_COLOR = 5 	# will fade the colors in rainbow\n\
\n\
std_msgs/ColorRGBA color #the color which will be used\n\
float32 frequency 		# in Hz\n\
float32 timeout 		# in s, requested mode will be executed for max timout s.\n\
						# default is 0 and meens no timeout.\n\
int32 pulses 			# spezifies the amount of pulses which will be executed.\n\
			 			# eg: mode = flash, pulses = 2. Meens the light will flash two times\n\
int8 priority 			# priority [-20,20] default = 0. Modes with same or higher priorities will \n\
						# be executed.\n\
================================================================================\n\
MSG: std_msgs/ColorRGBA\n\
float32 r\n\
float32 g\n\
float32 b\n\
float32 a\n\
";
  }

  static const char* value(const ::cob_light::SetLightModeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cob_light::SetLightModeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SetLightModeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cob_light::SetLightModeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cob_light::SetLightModeRequest_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    s << std::endl;
    Printer< ::cob_light::LightMode_<ContainerAllocator> >::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COB_LIGHT_MESSAGE_SETLIGHTMODEREQUEST_H
