(cl:defpackage cob_base_drive_chain-srv
  (:use )
  (:export
   "ELMORECORDERREADOUT"
   "<ELMORECORDERREADOUT-REQUEST>"
   "ELMORECORDERREADOUT-REQUEST"
   "<ELMORECORDERREADOUT-RESPONSE>"
   "ELMORECORDERREADOUT-RESPONSE"
   "ELMORECORDERCONFIG"
   "<ELMORECORDERCONFIG-REQUEST>"
   "ELMORECORDERCONFIG-REQUEST"
   "<ELMORECORDERCONFIG-RESPONSE>"
   "ELMORECORDERCONFIG-RESPONSE"
  ))

