/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/powerball/rpi_robotics_work/schunk_workspace/src/cob_command_tools/cob_script_server/srv/ComposeTrajectory.srv
 *
 */


#ifndef COB_SCRIPT_SERVER_MESSAGE_COMPOSETRAJECTORY_H
#define COB_SCRIPT_SERVER_MESSAGE_COMPOSETRAJECTORY_H

#include <ros/service_traits.h>


#include <cob_script_server/ComposeTrajectoryRequest.h>
#include <cob_script_server/ComposeTrajectoryResponse.h>


namespace cob_script_server
{

struct ComposeTrajectory
{

typedef ComposeTrajectoryRequest Request;
typedef ComposeTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ComposeTrajectory
} // namespace cob_script_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cob_script_server::ComposeTrajectory > {
  static const char* value()
  {
    return "c320ebb295f4a80333624b0ea716b1c1";
  }

  static const char* value(const ::cob_script_server::ComposeTrajectory&) { return value(); }
};

template<>
struct DataType< ::cob_script_server::ComposeTrajectory > {
  static const char* value()
  {
    return "cob_script_server/ComposeTrajectory";
  }

  static const char* value(const ::cob_script_server::ComposeTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::cob_script_server::ComposeTrajectoryRequest> should match 
// service_traits::MD5Sum< ::cob_script_server::ComposeTrajectory > 
template<>
struct MD5Sum< ::cob_script_server::ComposeTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cob_script_server::ComposeTrajectory >::value();
  }
  static const char* value(const ::cob_script_server::ComposeTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cob_script_server::ComposeTrajectoryRequest> should match 
// service_traits::DataType< ::cob_script_server::ComposeTrajectory > 
template<>
struct DataType< ::cob_script_server::ComposeTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::cob_script_server::ComposeTrajectory >::value();
  }
  static const char* value(const ::cob_script_server::ComposeTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cob_script_server::ComposeTrajectoryResponse> should match 
// service_traits::MD5Sum< ::cob_script_server::ComposeTrajectory > 
template<>
struct MD5Sum< ::cob_script_server::ComposeTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cob_script_server::ComposeTrajectory >::value();
  }
  static const char* value(const ::cob_script_server::ComposeTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cob_script_server::ComposeTrajectoryResponse> should match 
// service_traits::DataType< ::cob_script_server::ComposeTrajectory > 
template<>
struct DataType< ::cob_script_server::ComposeTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::cob_script_server::ComposeTrajectory >::value();
  }
  static const char* value(const ::cob_script_server::ComposeTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COB_SCRIPT_SERVER_MESSAGE_COMPOSETRAJECTORY_H
