/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/powerball/rpi_robotics_work/schunk_workspace/src/cob_driver/cob_phidgets/srv/SetDigitalSensor.srv
 *
 */


#ifndef COB_PHIDGETS_MESSAGE_SETDIGITALSENSORREQUEST_H
#define COB_PHIDGETS_MESSAGE_SETDIGITALSENSORREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cob_phidgets
{
template <class ContainerAllocator>
struct SetDigitalSensorRequest_
{
  typedef SetDigitalSensorRequest_<ContainerAllocator> Type;

  SetDigitalSensorRequest_()
    : uri()
    , state(0)  {
    }
  SetDigitalSensorRequest_(const ContainerAllocator& _alloc)
    : uri(_alloc)
    , state(0)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _uri_type;
  _uri_type uri;

   typedef int8_t _state_type;
  _state_type state;




  typedef boost::shared_ptr< ::cob_phidgets::SetDigitalSensorRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cob_phidgets::SetDigitalSensorRequest_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct SetDigitalSensorRequest_

typedef ::cob_phidgets::SetDigitalSensorRequest_<std::allocator<void> > SetDigitalSensorRequest;

typedef boost::shared_ptr< ::cob_phidgets::SetDigitalSensorRequest > SetDigitalSensorRequestPtr;
typedef boost::shared_ptr< ::cob_phidgets::SetDigitalSensorRequest const> SetDigitalSensorRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cob_phidgets::SetDigitalSensorRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cob_phidgets::SetDigitalSensorRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cob_phidgets

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/hydro/share/sensor_msgs/cmake/../msg'], 'cob_phidgets': ['/home/powerball/rpi_robotics_work/schunk_workspace/src/cob_driver/cob_phidgets/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cob_phidgets::SetDigitalSensorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cob_phidgets::SetDigitalSensorRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cob_phidgets::SetDigitalSensorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cob_phidgets::SetDigitalSensorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cob_phidgets::SetDigitalSensorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cob_phidgets::SetDigitalSensorRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cob_phidgets::SetDigitalSensorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "96cc93c2442fee91eb711a986476a959";
  }

  static const char* value(const ::cob_phidgets::SetDigitalSensorRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x96cc93c2442fee91ULL;
  static const uint64_t static_value2 = 0xeb711a986476a959ULL;
};

template<class ContainerAllocator>
struct DataType< ::cob_phidgets::SetDigitalSensorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cob_phidgets/SetDigitalSensorRequest";
  }

  static const char* value(const ::cob_phidgets::SetDigitalSensorRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cob_phidgets::SetDigitalSensorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string uri\n\
int8 state\n\
";
  }

  static const char* value(const ::cob_phidgets::SetDigitalSensorRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cob_phidgets::SetDigitalSensorRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.uri);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SetDigitalSensorRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cob_phidgets::SetDigitalSensorRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cob_phidgets::SetDigitalSensorRequest_<ContainerAllocator>& v)
  {
    s << indent << "uri: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.uri);
    s << indent << "state: ";
    Printer<int8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COB_PHIDGETS_MESSAGE_SETDIGITALSENSORREQUEST_H
