/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/powerball/rpi_robotics_work/schunk_workspace/src/cob_driver/cob_phidgets/srv/SetDataRate.srv
 *
 */


#ifndef COB_PHIDGETS_MESSAGE_SETDATARATE_H
#define COB_PHIDGETS_MESSAGE_SETDATARATE_H

#include <ros/service_traits.h>


#include <cob_phidgets/SetDataRateRequest.h>
#include <cob_phidgets/SetDataRateResponse.h>


namespace cob_phidgets
{

struct SetDataRate
{

typedef SetDataRateRequest Request;
typedef SetDataRateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetDataRate
} // namespace cob_phidgets


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cob_phidgets::SetDataRate > {
  static const char* value()
  {
    return "2fe4d4dafc6b478c7e506a02543a3197";
  }

  static const char* value(const ::cob_phidgets::SetDataRate&) { return value(); }
};

template<>
struct DataType< ::cob_phidgets::SetDataRate > {
  static const char* value()
  {
    return "cob_phidgets/SetDataRate";
  }

  static const char* value(const ::cob_phidgets::SetDataRate&) { return value(); }
};


// service_traits::MD5Sum< ::cob_phidgets::SetDataRateRequest> should match 
// service_traits::MD5Sum< ::cob_phidgets::SetDataRate > 
template<>
struct MD5Sum< ::cob_phidgets::SetDataRateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cob_phidgets::SetDataRate >::value();
  }
  static const char* value(const ::cob_phidgets::SetDataRateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cob_phidgets::SetDataRateRequest> should match 
// service_traits::DataType< ::cob_phidgets::SetDataRate > 
template<>
struct DataType< ::cob_phidgets::SetDataRateRequest>
{
  static const char* value()
  {
    return DataType< ::cob_phidgets::SetDataRate >::value();
  }
  static const char* value(const ::cob_phidgets::SetDataRateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cob_phidgets::SetDataRateResponse> should match 
// service_traits::MD5Sum< ::cob_phidgets::SetDataRate > 
template<>
struct MD5Sum< ::cob_phidgets::SetDataRateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cob_phidgets::SetDataRate >::value();
  }
  static const char* value(const ::cob_phidgets::SetDataRateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cob_phidgets::SetDataRateResponse> should match 
// service_traits::DataType< ::cob_phidgets::SetDataRate > 
template<>
struct DataType< ::cob_phidgets::SetDataRateResponse>
{
  static const char* value()
  {
    return DataType< ::cob_phidgets::SetDataRate >::value();
  }
  static const char* value(const ::cob_phidgets::SetDataRateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COB_PHIDGETS_MESSAGE_SETDATARATE_H
