/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/powerball/rpi_robotics_work/schunk_workspace/src/cob_driver/cob_phidgets/srv/SetTriggerValue.srv
 *
 */


#ifndef COB_PHIDGETS_MESSAGE_SETTRIGGERVALUEREQUEST_H
#define COB_PHIDGETS_MESSAGE_SETTRIGGERVALUEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cob_phidgets
{
template <class ContainerAllocator>
struct SetTriggerValueRequest_
{
  typedef SetTriggerValueRequest_<ContainerAllocator> Type;

  SetTriggerValueRequest_()
    : index(0)
    , trigger_value(0)  {
    }
  SetTriggerValueRequest_(const ContainerAllocator& _alloc)
    : index(0)
    , trigger_value(0)  {
    }



   typedef int8_t _index_type;
  _index_type index;

   typedef uint16_t _trigger_value_type;
  _trigger_value_type trigger_value;




  typedef boost::shared_ptr< ::cob_phidgets::SetTriggerValueRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cob_phidgets::SetTriggerValueRequest_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct SetTriggerValueRequest_

typedef ::cob_phidgets::SetTriggerValueRequest_<std::allocator<void> > SetTriggerValueRequest;

typedef boost::shared_ptr< ::cob_phidgets::SetTriggerValueRequest > SetTriggerValueRequestPtr;
typedef boost::shared_ptr< ::cob_phidgets::SetTriggerValueRequest const> SetTriggerValueRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cob_phidgets::SetTriggerValueRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cob_phidgets::SetTriggerValueRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cob_phidgets

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/hydro/share/sensor_msgs/cmake/../msg'], 'cob_phidgets': ['/home/powerball/rpi_robotics_work/schunk_workspace/src/cob_driver/cob_phidgets/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cob_phidgets::SetTriggerValueRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cob_phidgets::SetTriggerValueRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cob_phidgets::SetTriggerValueRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cob_phidgets::SetTriggerValueRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cob_phidgets::SetTriggerValueRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cob_phidgets::SetTriggerValueRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cob_phidgets::SetTriggerValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f5eabd2487a9b62214c60cbc4be257ee";
  }

  static const char* value(const ::cob_phidgets::SetTriggerValueRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf5eabd2487a9b622ULL;
  static const uint64_t static_value2 = 0x14c60cbc4be257eeULL;
};

template<class ContainerAllocator>
struct DataType< ::cob_phidgets::SetTriggerValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cob_phidgets/SetTriggerValueRequest";
  }

  static const char* value(const ::cob_phidgets::SetTriggerValueRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cob_phidgets::SetTriggerValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 index\n\
uint16 trigger_value\n\
";
  }

  static const char* value(const ::cob_phidgets::SetTriggerValueRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cob_phidgets::SetTriggerValueRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.index);
      stream.next(m.trigger_value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SetTriggerValueRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cob_phidgets::SetTriggerValueRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cob_phidgets::SetTriggerValueRequest_<ContainerAllocator>& v)
  {
    s << indent << "index: ";
    Printer<int8_t>::stream(s, indent + "  ", v.index);
    s << indent << "trigger_value: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.trigger_value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COB_PHIDGETS_MESSAGE_SETTRIGGERVALUEREQUEST_H
