(cl:defpackage cob_phidgets-srv
  (:use )
  (:export
   "SETTRIGGERVALUE"
   "<SETTRIGGERVALUE-REQUEST>"
   "SETTRIGGERVALUE-REQUEST"
   "<SETTRIGGERVALUE-RESPONSE>"
   "SETTRIGGERVALUE-RESPONSE"
   "SETDATARATE"
   "<SETDATARATE-REQUEST>"
   "SETDATARATE-REQUEST"
   "<SETDATARATE-RESPONSE>"
   "SETDATARATE-RESPONSE"
   "SETDIGITALSENSOR"
   "<SETDIGITALSENSOR-REQUEST>"
   "SETDIGITALSENSOR-REQUEST"
   "<SETDIGITALSENSOR-RESPONSE>"
   "SETDIGITALSENSOR-RESPONSE"
  ))

