(cl:defpackage cob_light-msg
  (:use )
  (:export
   "<LIGHTMODE>"
   "LIGHTMODE"
   "<SETLIGHTMODEFEEDBACK>"
   "SETLIGHTMODEFEEDBACK"
   "<SETLIGHTMODEACTIONFEEDBACK>"
   "SETLIGHTMODEACTIONFEEDBACK"
   "<SETLIGHTMODEGOAL>"
   "SETLIGHTMODEGOAL"
   "<SETLIGHTMODEACTION>"
   "SETLIGHTMODEACTION"
   "<SETLIGHTMODEACTIONRESULT>"
   "SETLIGHTMODEACTIONRESULT"
   "<SETLIGHTMODEACTIONGOAL>"
   "SETLIGHTMODEACTIONGOAL"
   "<SETLIGHTMODERESULT>"
   "SETLIGHTMODERESULT"
  ))

