; Auto-generated. Do not edit!


(cl:in-package cob_light-msg)


;//! \htmlinclude SetLightModeResult.msg.html

(cl:defclass <SetLightModeResult> (roslisp-msg-protocol:ros-message)
  ((active_mode
    :reader active_mode
    :initarg :active_mode
    :type cl:fixnum
    :initform 0)
   (active_priority
    :reader active_priority
    :initarg :active_priority
    :type cl:fixnum
    :initform 0))
)

(cl:defclass SetLightModeResult (<SetLightModeResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SetLightModeResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SetLightModeResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cob_light-msg:<SetLightModeResult> is deprecated: use cob_light-msg:SetLightModeResult instead.")))

(cl:ensure-generic-function 'active_mode-val :lambda-list '(m))
(cl:defmethod active_mode-val ((m <SetLightModeResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cob_light-msg:active_mode-val is deprecated.  Use cob_light-msg:active_mode instead.")
  (active_mode m))

(cl:ensure-generic-function 'active_priority-val :lambda-list '(m))
(cl:defmethod active_priority-val ((m <SetLightModeResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cob_light-msg:active_priority-val is deprecated.  Use cob_light-msg:active_priority instead.")
  (active_priority m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SetLightModeResult>) ostream)
  "Serializes a message object of type '<SetLightModeResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'active_mode)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'active_priority)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SetLightModeResult>) istream)
  "Deserializes a message object of type '<SetLightModeResult>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'active_mode)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'active_priority)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SetLightModeResult>)))
  "Returns string type for a message object of type '<SetLightModeResult>"
  "cob_light/SetLightModeResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SetLightModeResult)))
  "Returns string type for a message object of type 'SetLightModeResult"
  "cob_light/SetLightModeResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SetLightModeResult>)))
  "Returns md5sum for a message object of type '<SetLightModeResult>"
  "18daff0db423efd323f68cd039226daa")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SetLightModeResult)))
  "Returns md5sum for a message object of type 'SetLightModeResult"
  "18daff0db423efd323f68cd039226daa")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SetLightModeResult>)))
  "Returns full string definition for message of type '<SetLightModeResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# The results~%uint8 active_mode~%uint8 active_priority~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SetLightModeResult)))
  "Returns full string definition for message of type 'SetLightModeResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# The results~%uint8 active_mode~%uint8 active_priority~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SetLightModeResult>))
  (cl:+ 0
     1
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SetLightModeResult>))
  "Converts a ROS message object to a list"
  (cl:list 'SetLightModeResult
    (cl:cons ':active_mode (active_mode msg))
    (cl:cons ':active_priority (active_priority msg))
))
