; Auto-generated. Do not edit!


(cl:in-package cob_script_server-msg)


;//! \htmlinclude ScriptFeedback.msg.html

(cl:defclass <ScriptFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass ScriptFeedback (<ScriptFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ScriptFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ScriptFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cob_script_server-msg:<ScriptFeedback> is deprecated: use cob_script_server-msg:ScriptFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ScriptFeedback>) ostream)
  "Serializes a message object of type '<ScriptFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ScriptFeedback>) istream)
  "Deserializes a message object of type '<ScriptFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ScriptFeedback>)))
  "Returns string type for a message object of type '<ScriptFeedback>"
  "cob_script_server/ScriptFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ScriptFeedback)))
  "Returns string type for a message object of type 'ScriptFeedback"
  "cob_script_server/ScriptFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ScriptFeedback>)))
  "Returns md5sum for a message object of type '<ScriptFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ScriptFeedback)))
  "Returns md5sum for a message object of type 'ScriptFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ScriptFeedback>)))
  "Returns full string definition for message of type '<ScriptFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback definition~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ScriptFeedback)))
  "Returns full string definition for message of type 'ScriptFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback definition~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ScriptFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ScriptFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ScriptFeedback
))
