; Auto-generated. Do not edit!


(cl:in-package cob_script_server-msg)


;//! \htmlinclude StateActionGoal.msg.html

(cl:defclass <StateActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type cob_script_server-msg:StateGoal
    :initform (cl:make-instance 'cob_script_server-msg:StateGoal)))
)

(cl:defclass StateActionGoal (<StateActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <StateActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'StateActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cob_script_server-msg:<StateActionGoal> is deprecated: use cob_script_server-msg:StateActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <StateActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cob_script_server-msg:header-val is deprecated.  Use cob_script_server-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <StateActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cob_script_server-msg:goal_id-val is deprecated.  Use cob_script_server-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <StateActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cob_script_server-msg:goal-val is deprecated.  Use cob_script_server-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <StateActionGoal>) ostream)
  "Serializes a message object of type '<StateActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <StateActionGoal>) istream)
  "Deserializes a message object of type '<StateActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<StateActionGoal>)))
  "Returns string type for a message object of type '<StateActionGoal>"
  "cob_script_server/StateActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'StateActionGoal)))
  "Returns string type for a message object of type 'StateActionGoal"
  "cob_script_server/StateActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<StateActionGoal>)))
  "Returns md5sum for a message object of type '<StateActionGoal>"
  "f58b9a5222bb93570e16f2c52ca3ec7b")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'StateActionGoal)))
  "Returns md5sum for a message object of type 'StateActionGoal"
  "f58b9a5222bb93570e16f2c52ca3ec7b")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<StateActionGoal>)))
  "Returns full string definition for message of type '<StateActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%StateGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.secs: seconds (stamp_secs) since epoch~%# * stamp.nsecs: nanoseconds since stamp_secs~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: cob_script_server/StateGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%cob_script_server/ScriptState state~%~%================================================================================~%MSG: cob_script_server/ScriptState~%Header header~%int16 number~%string function_name~%string component_name~%string parameter_name~%string full_graph_name~%~%# Possible execution states~%byte UNKNOWN=0~%byte ACTIVE=1~%byte SUCCEEDED=2~%byte FAILED=3~%byte PAUSED=4~%~%byte state # state of execution~%int16 error_code # current error_code for state~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'StateActionGoal)))
  "Returns full string definition for message of type 'StateActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%StateGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.secs: seconds (stamp_secs) since epoch~%# * stamp.nsecs: nanoseconds since stamp_secs~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: cob_script_server/StateGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%cob_script_server/ScriptState state~%~%================================================================================~%MSG: cob_script_server/ScriptState~%Header header~%int16 number~%string function_name~%string component_name~%string parameter_name~%string full_graph_name~%~%# Possible execution states~%byte UNKNOWN=0~%byte ACTIVE=1~%byte SUCCEEDED=2~%byte FAILED=3~%byte PAUSED=4~%~%byte state # state of execution~%int16 error_code # current error_code for state~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <StateActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <StateActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'StateActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
