/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_golems_amino_Lib */

#ifndef _Included_org_golems_amino_Lib
#define _Included_org_golems_amino_Lib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_golems_amino_Lib
 * Method:    mem_region_create
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_golems_amino_Lib_mem_1region_1create
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_golems_amino_Lib
 * Method:    mem_region_release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_golems_amino_Lib_mem_1region_1release
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_golems_amino_Lib
 * Method:    mem_region_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_golems_amino_Lib_mem_1region_1destroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
